package functions

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/functions/dates.go
 * 
 * Don't edit this file. Edit models/functions/dates.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type DateGenerator struct {
  
      startDate []float64
    
  
      startMonth []float64
    
  
      startYear []float64
    
  

  
}

func (m *DateGenerator) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.startDate = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.startMonth = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.startYear = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildDateGenerator() sim.TimeSteppingModel {
	result := DateGenerator{}
	return &result
}

func init() {
	sim.Catalog["DateGenerator"] = buildDateGenerator
}

func (m *DateGenerator)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  startDateDims := []string{
      }
  
  startMonthDims := []string{
      }
  
  startYearDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("startDate",0,"",[]float64{ 0, 0 },"",startDateDims),
  sim.DescribeParameter("startMonth",0,"",[]float64{ 0, 0 },"",startMonthDims),
  sim.DescribeParameter("startYear",0,"",[]float64{ 0, 0 },"",startYearDims),}

  result.Inputs = []string{
  "tick",}
  result.Outputs = []string{
  "date","month","year","dayOfYear",}

  result.States = []string{
  }

  result.Dimensions = []string{
      }
	return result
}

func (m *DateGenerator) InitialiseDimensions(dims []int) {
  
}

func (m *DateGenerator) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *DateGenerator) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,0)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,0)
  //   

  //   if result==nil {
  //     result = data.NewArray2D[float64](stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *DateGenerator) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running DateGenerator for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      startdate := m.startDate[i%len(m.startDate)]
      startmonth := m.startMonth[i%len(m.startMonth)]
      startyear := m.startYear[i%len(m.startYear)]
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      

      
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{tick <nil>}",tmpTS.Shape())
      tick := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      date := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      dateSliced := date.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      month := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      monthSliced := month.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      year := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      yearSliced := year.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      dayofyear := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      dayofyearSliced := dayofyear.Unroll()
      
      

       dateGenerator(tick,startdate,startmonth,startyear,dateSliced,monthSliced,yearSliced,dayofyearSliced)

      
      
      date.Reroll()
      
      month.Reroll()
      
      year.Reroll()
      
      dayofyear.Reroll()
      
      

      
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 4)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
