language: go

os:
  - linux
  - osx
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image xcode7.2

sudo: required

go:
  - 1.x

before_install:
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then sudo apt-get install -y libhdf5-serial-dev python3-venv; fi
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then brew install hdf5; fi

script:
  - python3 --version
  - ./build/bootstrap-test-env.sh
  - OW_TEST_PATH=$PWD/test/files go test ./...
  - ./build/build.sh
  - ./build/run_test.sh
  - ls -a


