language: go

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx

sudo: required

go:
  - 1.x

before_install:
  - ./build/ci/$TRAVIS_OS_NAME.sh
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi

script:
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi
  - python3 --version
  - ./build/bootstrap-test-env.sh
  - OW_TEST_PATH=$PWD/test/files go test ./...
  - ./build/build.sh
  - ./build/run_test.sh
  - ls -a


