language: go

# os:
#   - linux
#   - osx
#   - windows

jobs:
  include:
    - os: linux
      dist: bionic
      before_install:
        - ./build/ci/$TRAVIS_OS_NAME.sh
        - python3 -m venv ow-test
        - source ow-test/bin/activate
    # - os: osx
    #   osx_image: xcode12.2
    #   before_install:
    #     - ./build/ci/$TRAVIS_OS_NAME.sh
    #     - python3 -m venv ow-test
    #     - source ow-test/bin/activate
    - os: windows
      before_install:
        - ./build/ci/$TRAVIS_OS_NAME.sh
        - source compilation_vars.txt
        # - source ow-test/Scripts/activate

sudo: required

go:
  - 1.x

# before_install:
#   - ./build/ci/$TRAVIS_OS_NAME.sh
#   - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi

script:
  - export VENV_DIR=bin
  # - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi
  - python3 --version
  - ./build/bootstrap-test-env.sh
  - OW_TEST_PATH=$PWD/test/files go test -v ./...
  - ./build/build.sh
  - ./build/run_test.sh
  - ls -al


