language: go

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH='/c/Python37:/c/Python37/Scripts:$PATH'
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
sudo: required

go:
  - 1.x

before_install:
  - ./build/ci/$TRAVIS_OS_NAME.sh
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi

script:
  - export VENV_DIR=bin
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then source compilation_vars.txt; fi
  - python3 --version
  - ./build/bootstrap-test-env.sh
  - OW_TEST_PATH=$PWD/test/files go test -v ./...
  - ./build/build.sh
  - ./build/run_test.sh
  - ls -al


