package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/routing/instream_particulate_nutrient.go
 * 
 * Don't edit this file. Edit models/routing/instream_particulate_nutrient.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type InstreamParticulateNutrient struct {
  
      particulateNutrientConcentration []float64
    
  
      soilPercentFine []float64
    
  
      durationInSeconds []float64
    
  

  
}

func (m *InstreamParticulateNutrient) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.particulateNutrientConcentration = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.soilPercentFine = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.durationInSeconds = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildInstreamParticulateNutrient() sim.TimeSteppingModel {
	result := InstreamParticulateNutrient{}
	return &result
}

func init() {
	sim.Catalog["InstreamParticulateNutrient"] = buildInstreamParticulateNutrient
}

func (m *InstreamParticulateNutrient)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  particulateNutrientConcentrationDims := []string{
      }
  
  soilPercentFineDims := []string{
      }
  
  durationInSecondsDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("particulateNutrientConcentration",0,"Proportion of sediment mass",[]float64{ 0, 1 }," ",particulateNutrientConcentrationDims),
  sim.DescribeParameter("soilPercentFine",0,"",[]float64{ 0, 0 },"",soilPercentFineDims),
  sim.DescribeParameter("durationInSeconds",86400,"Timestep",[]float64{ 1, 86400 }," ",durationInSecondsDims),}

  result.Inputs = []string{
  "incomingMassUpstream","incomingMassLateral","reachVolume","outflow","streambankErosion","lateralSediment","floodplainDepositionFraction","channelDepositionFraction",}
  result.Outputs = []string{
  "loadDeposited","loadFromStreambank","loadDownstream","loadToFloodplain",}

  result.States = []string{
  "instreamStoredMass","channelStoredMass",}

  result.Dimensions = []string{
      }
	return result
}

func (m *InstreamParticulateNutrient) InitialiseDimensions(dims []int) {
  
}

func (m *InstreamParticulateNutrient) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *InstreamParticulateNutrient) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,2)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,2)
  //   
	// 	stateSet[0] = 0 // instreamStoredMass
  //   
	// 	stateSet[1] = 0 // channelStoredMass
  //   

  //   if result==nil {
  //     result = data.NewArray2D[float64](stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *InstreamParticulateNutrient) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running InstreamParticulateNutrient for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      particulatenutrientconcentration := m.particulateNutrientConcentration[i%len(m.particulateNutrientConcentration)]
      soilpercentfine := m.soilPercentFine[i%len(m.soilPercentFine)]
      durationinseconds := m.durationInSeconds[i%len(m.durationInSeconds)]
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      instreamstoredmass := initialStates[0]
      
      channelstoredmass := initialStates[1]
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{incomingMassUpstream <nil>}",tmpTS.Shape())
      incomingmassupstream := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{incomingMassLateral <nil>}",tmpTS.Shape())
      incomingmasslateral := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{reachVolume <nil>}",tmpTS.Shape())
      reachvolume := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{outflow <nil>}",tmpTS.Shape())
      outflow := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{streambankErosion <nil>}",tmpTS.Shape())
      streambankerosion := cellInputs.Slice([]int{ 4,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{lateralSediment <nil>}",tmpTS.Shape())
      lateralsediment := cellInputs.Slice([]int{ 5,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{floodplainDepositionFraction <nil>}",tmpTS.Shape())
      floodplaindepositionfraction := cellInputs.Slice([]int{ 6,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{channelDepositionFraction <nil>}",tmpTS.Shape())
      channeldepositionfraction := cellInputs.Slice([]int{ 7,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      loaddeposited := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      loadfromstreambank := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      loaddownstream := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      loadtofloodplain := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      

      instreamstoredmass,channelstoredmass= instreamParticulateNutrient(incomingmassupstream,incomingmasslateral,reachvolume,outflow,streambankerosion,lateralsediment,floodplaindepositionfraction,channeldepositionfraction,instreamstoredmass,channelstoredmass,particulatenutrientconcentration,soilpercentfine,durationinseconds,loaddeposited,loadfromstreambank,loaddownstream,loadtofloodplain)

      
      
      initialStates[0] = instreamstoredmass
      
      initialStates[1] = channelstoredmass
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 4)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
