package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from src/github.com/flowmatters/openwater-core/models/routing/muskingum.go
 * 
 * Don't edit this file. Edit src/github.com/flowmatters/openwater-core/models/routing/muskingum.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type Muskingum struct {
  K data.ND1Float64
  X data.ND1Float64
  DeltaT data.ND1Float64
  
}

func (m *Muskingum) ApplyParameters(parameters data.ND2Float64) {
  // fmt.Println(parameters)
  // fmt.Println(parameters.Shape())
  nSets := parameters.Len(sim.DIMP_CELL)
  // fmt.Println(nSets)
  m.K = parameters.Slice([]int{ 0, 0}, []int{ 1, nSets}, nil).(data.ND1Float64)
  m.X = parameters.Slice([]int{ 1, 0}, []int{ 1, nSets}, nil).(data.ND1Float64)
  m.DeltaT = parameters.Slice([]int{ 2, 0}, []int{ 1, nSets}, nil).(data.ND1Float64)
  
}


func buildMuskingum() sim.TimeSteppingModel {
	result := Muskingum{}
	return &result
}

func init() {
	sim.Catalog["Muskingum"] = buildMuskingum
}

func (m *Muskingum)  Description() sim.ModelDescription{
	var result sim.ModelDescription
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("K",0,""),
  sim.DescribeParameter("X",0,""),
  sim.DescribeParameter("DeltaT",0,""),}

  result.Inputs = []string{
  "inflow","lateral",}
  result.Outputs = []string{
  "outflow",}

  result.States = []string{
  "S","prevInflow","prevOutflow",}

	return result
}




func (m *Muskingum) InitialiseStates(n int) data.ND2Float64 {
  // Zero states
	var result = data.NewArray2DFloat64(n,3)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,3)
  //   
	// 	stateSet[0] = 0 // S
  //   
	// 	stateSet[1] = 0 // prevInflow
  //   
	// 	stateSet[2] = 0 // prevOutflow
  //   

  //   if result==nil {
  //     result = data.NewArray2DFloat64(stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *Muskingum) Run(inputs data.ND3Float64, states data.ND2Float64, outputs data.ND3Float64) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3DFloat64( 1, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  // fmt.Println("Running Muskingum for ",numCells,"cells")
  for i := 0; i < numCells; i++ {
    outputPosSlice[sim.DIMO_CELL] = i
    statesPosSlice[sim.DIMS_CELL] = i
    inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

    
    // fmt.Println("K=",m.K)
		k := m.K.Get1(i%m.K.Len1())
    
    // fmt.Println("X=",m.X)
		x := m.X.Get1(i%m.X.Len1())
    
    // fmt.Println("DeltaT=",m.DeltaT)
		deltat := m.DeltaT.Get1(i%m.DeltaT.Len1())
    

    // fmt.Println("i",i)
    // fmt.Println("States",states.Shape())
    // fmt.Println("Tmp2",tmp2.Shape())
    
    initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).(data.ND1Float64)
    
    // fmt.Println("IS Shape",initialStates.Shape())
    // fmt.Println("IS",initialStates)

    
    
    s := initialStates.Get1(0)
    
    previnflow := initialStates.Get1(1)
    
    prevoutflow := initialStates.Get1(2)
    
    

//    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

		cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
//    fmt.Println("cellInputs Shape",cellInputs.Shape())
    
//    fmt.Println("{inflow m^3.s^-1}",tmpTS.Shape())
		inflow := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
    
//    fmt.Println("{lateral m^3.s^-1}",tmpTS.Shape())
		lateral := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
    

    

    
    
    outputPosSlice[sim.DIMO_OUTPUT] = 0
    outflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
    
    

		s,previnflow,prevoutflow= muskingum(inflow,lateral,s,previnflow,prevoutflow,k,x,deltat,outflow)

    
    
    initialStates.Set1(0, s)
    
    initialStates.Set1(1, previnflow)
    
    initialStates.Set1(2, prevoutflow)
    
    

//		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 1)
    
	}

//	return result
}
