package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/routing/storage_routing.go
 * 
 * Don't edit this file. Edit models/routing/storage_routing.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type StorageRouting struct {
  
      InflowBias []float64
    
  
      RoutingConstant []float64
    
  
      RoutingPower []float64
    
  
      area []float64
    
  
      deadStorage []float64
    
  
      DeltaT []float64
    
  

  
}

func (m *StorageRouting) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.InflowBias = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.RoutingConstant = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.RoutingPower = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.area = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.deadStorage = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.DeltaT = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildStorageRouting() sim.TimeSteppingModel {
	result := StorageRouting{}
	return &result
}

func init() {
	sim.Catalog["StorageRouting"] = buildStorageRouting
}

func (m *StorageRouting)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  InflowBiasDims := []string{
      }
  
  RoutingConstantDims := []string{
      }
  
  RoutingPowerDims := []string{
      }
  
  areaDims := []string{
      }
  
  deadStorageDims := []string{
      }
  
  DeltaTDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("InflowBias",0,"",[]float64{ 0, 0 },"",InflowBiasDims),
  sim.DescribeParameter("RoutingConstant",0,"",[]float64{ 0, 0 },"",RoutingConstantDims),
  sim.DescribeParameter("RoutingPower",0,"",[]float64{ 0, 0 },"",RoutingPowerDims),
  sim.DescribeParameter("area",0,"",[]float64{ 0, 0 },"",areaDims),
  sim.DescribeParameter("deadStorage",0,"",[]float64{ 0, 0 },"",deadStorageDims),
  sim.DescribeParameter("DeltaT",86400,"Timestep",[]float64{ 1, 86400 }," ",DeltaTDims),}

  result.Inputs = []string{
  "inflow","lateral","rainfall","evap",}
  result.Outputs = []string{
  "outflow","storage",}

  result.States = []string{
  "S","prevInflow","prevOutflow",}

  result.Dimensions = []string{
      }
	return result
}

func (m *StorageRouting) InitialiseDimensions(dims []int) {
  
}

func (m *StorageRouting) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *StorageRouting) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,3)
	return result
}



func (m *StorageRouting) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 2, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      inflowbias := m.InflowBias[i%len(m.InflowBias)]
      routingconstant := m.RoutingConstant[i%len(m.RoutingConstant)]
      routingpower := m.RoutingPower[i%len(m.RoutingPower)]
      area := m.area[i%len(m.area)]
      deadstorage := m.deadStorage[i%len(m.deadStorage)]
      deltat := m.DeltaT[i%len(m.DeltaT)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      s := initialStates[0]
      
      previnflow := initialStates[1]
      
      prevoutflow := initialStates[2]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      inflow := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      lateral := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      rainfall := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      evap := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      outflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      outflowSliced := outflow.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      storage := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      storageSliced := storage.Unroll()
      
      

      s,previnflow,prevoutflow= storageRouting(inflow,lateral,rainfall,evap,s,previnflow,prevoutflow,inflowbias,routingconstant,routingpower,area,deadstorage,deltat,outflowSliced,storageSliced)

      
      
      outflow.Reroll()
      
      storage.Reroll()
      
      

      
      
      initialStates[0] = s
      
      initialStates[1] = previnflow
      
      initialStates[2] = prevoutflow
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
