package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from ./models/routing/storage_routing.go
 * 
 * Don't edit this file. Edit ./models/routing/storage_routing.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type StorageRouting struct {
  InflowBias data.ND1Float64
  RoutingConstant data.ND1Float64
  RoutingPower data.ND1Float64
  area data.ND1Float64
  deadStorage data.ND1Float64
  DeltaT data.ND1Float64
  
}

func (m *StorageRouting) ApplyParameters(parameters data.ND2Float64) {

  nSets := parameters.Len(sim.DIMP_CELL)
  newShape := []int{nSets}

  m.InflowBias = parameters.Slice([]int{ 0, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  m.RoutingConstant = parameters.Slice([]int{ 1, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  m.RoutingPower = parameters.Slice([]int{ 2, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  m.area = parameters.Slice([]int{ 3, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  m.deadStorage = parameters.Slice([]int{ 4, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  m.DeltaT = parameters.Slice([]int{ 5, 0}, []int{ 1, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  
}


func buildStorageRouting() sim.TimeSteppingModel {
	result := StorageRouting{}
	return &result
}

func init() {
	sim.Catalog["StorageRouting"] = buildStorageRouting
}

func (m *StorageRouting)  Description() sim.ModelDescription{
	var result sim.ModelDescription
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("InflowBias",0,"",[]float64{ 0, 0 },""),
  sim.DescribeParameter("RoutingConstant",0,"",[]float64{ 0, 0 },""),
  sim.DescribeParameter("RoutingPower",0,"",[]float64{ 0, 0 },""),
  sim.DescribeParameter("area",0,"",[]float64{ 0, 0 },""),
  sim.DescribeParameter("deadStorage",0,"",[]float64{ 0, 0 },""),
  sim.DescribeParameter("DeltaT",86400,"Timestep",[]float64{ 1, 86400 }," "),}

  result.Inputs = []string{
  "inflow","lateral","rainfall","evap",}
  result.Outputs = []string{
  "outflow","storage",}

  result.States = []string{
  "S","prevInflow","prevOutflow",}

	return result
}




func (m *StorageRouting) InitialiseStates(n int) data.ND2Float64 {
  // Zero states
	var result = data.NewArray2DFloat64(n,3)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,3)
  //   
	// 	stateSet[0] = 0 // S
  //   
	// 	stateSet[1] = 0 // prevInflow
  //   
	// 	stateSet[2] = 0 // prevOutflow
  //   

  //   if result==nil {
  //     result = data.NewArray2DFloat64(stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *StorageRouting) Run(inputs data.ND3Float64, states data.ND2Float64, outputs data.ND3Float64) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3DFloat64( 2, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running StorageRouting for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      
      // fmt.Println("InflowBias=",m.InflowBias)
      inflowbias := m.InflowBias.Get1(i%m.InflowBias.Len1())
      
      // fmt.Println("RoutingConstant=",m.RoutingConstant)
      routingconstant := m.RoutingConstant.Get1(i%m.RoutingConstant.Len1())
      
      // fmt.Println("RoutingPower=",m.RoutingPower)
      routingpower := m.RoutingPower.Get1(i%m.RoutingPower.Len1())
      
      // fmt.Println("area=",m.area)
      area := m.area.Get1(i%m.area.Len1())
      
      // fmt.Println("deadStorage=",m.deadStorage)
      deadstorage := m.deadStorage.Get1(i%m.deadStorage.Len1())
      
      // fmt.Println("DeltaT=",m.DeltaT)
      deltat := m.DeltaT.Get1(i%m.DeltaT.Len1())
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).(data.ND1Float64)
      

      
      
      s := initialStates.Get1(0)
      
      previnflow := initialStates.Get1(1)
      
      prevoutflow := initialStates.Get1(2)
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{inflow m^3.s^-1}",tmpTS.Shape())
      inflow := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{lateral m^3.s^-1}",tmpTS.Shape())
      lateral := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{rainfall mm}",tmpTS.Shape())
      rainfall := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{evap mm}",tmpTS.Shape())
      evap := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      outflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      storage := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      

      s,previnflow,prevoutflow= storageRouting(inflow,lateral,rainfall,evap,s,previnflow,prevoutflow,inflowbias,routingconstant,routingpower,area,deadstorage,deltat,outflow,storage)

      
      
      initialStates.Set1(0, s)
      
      initialStates.Set1(1, previnflow)
      
      initialStates.Set1(2, prevoutflow)
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 2)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
