package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/routing/instream_coarse_sediment.go
 * 
 * Don't edit this file. Edit models/routing/instream_coarse_sediment.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type InstreamCoarseSediment struct {
  
      durationInSeconds []float64
    
  

  
}

func (m *InstreamCoarseSediment) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.durationInSeconds = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildInstreamCoarseSediment() sim.TimeSteppingModel {
	result := InstreamCoarseSediment{}
	return &result
}

func init() {
	sim.Catalog["InstreamCoarseSediment"] = buildInstreamCoarseSediment
}

func (m *InstreamCoarseSediment)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  durationInSecondsDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("durationInSeconds",86400,"Timestep",[]float64{ 1, 86400 }," ",durationInSecondsDims),}

  result.Inputs = []string{
  "upstreamMass","lateralMass","reachLocalMass",}
  result.Outputs = []string{
  "loadDownstream",}

  result.States = []string{
  "channelStore","totalStoredMass",}

  result.Dimensions = []string{
      }
	return result
}

func (m *InstreamCoarseSediment) InitialiseDimensions(dims []int) {
  
}

func (m *InstreamCoarseSediment) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *InstreamCoarseSediment) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,2)
	return result
}



func (m *InstreamCoarseSediment) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 1, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      durationinseconds := m.durationInSeconds[i%len(m.durationInSeconds)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      channelstore := initialStates[0]
      
      totalstoredmass := initialStates[1]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      upstreammass := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      lateralmass := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      reachlocalmass := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      loaddownstream := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      loaddownstreamSliced := loaddownstream.Unroll()
      
      

      channelstore,totalstoredmass= instreamCoarseSediment(upstreammass,lateralmass,reachlocalmass,channelstore,totalstoredmass,durationinseconds,loaddownstreamSliced)

      
      
      loaddownstream.Reroll()
      
      

      
      
      initialStates[0] = channelstore
      
      initialStates[1] = totalstoredmass
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
