package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/routing/decay.go
 * 
 * Don't edit this file. Edit models/routing/decay.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type ConstituentDecay struct {
  
      X []float64
    
  
      halfLife []float64
    
  
      DeltaT []float64
    
  

  
}

func (m *ConstituentDecay) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.X = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.halfLife = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.DeltaT = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildConstituentDecay() sim.TimeSteppingModel {
	result := ConstituentDecay{}
	return &result
}

func init() {
	sim.Catalog["ConstituentDecay"] = buildConstituentDecay
}

func (m *ConstituentDecay)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  XDims := []string{
      }
  
  halfLifeDims := []string{
      }
  
  DeltaTDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("X",0,"Weighting",[]float64{ 0, 1 }," ",XDims),
  sim.DescribeParameter("halfLife",0,"",[]float64{ 0, 0 },"",halfLifeDims),
  sim.DescribeParameter("DeltaT",86400,"Timestep",[]float64{ 1, 86400 }," ",DeltaTDims),}

  result.Inputs = []string{
  "inflowLoad","lateralLoad","inflow","outflow","storage",}
  result.Outputs = []string{
  "decayedLoad","outflowLoad",}

  result.States = []string{
  "storedMass",}

  result.Dimensions = []string{
      }
	return result
}

func (m *ConstituentDecay) InitialiseDimensions(dims []int) {
  
}

func (m *ConstituentDecay) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *ConstituentDecay) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,1)
	return result
}



func (m *ConstituentDecay) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 2, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      x := m.X[i%len(m.X)]
      halflife := m.halfLife[i%len(m.halfLife)]
      deltat := m.DeltaT[i%len(m.DeltaT)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      storedmass := initialStates[0]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      inflowload := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      lateralload := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      inflow := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      outflow := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      storage := cellInputs.Slice([]int{ 4,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      decayedload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      decayedloadSliced := decayedload.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      outflowload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      outflowloadSliced := outflowload.Unroll()
      
      

      storedmass= constituentDecay(inflowload,lateralload,inflow,outflow,storage,storedmass,x,halflife,deltat,decayedloadSliced,outflowloadSliced)

      
      
      decayedload.Reroll()
      
      outflowload.Reroll()
      
      

      
      
      initialStates[0] = storedmass
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
