package routing

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from ./models/routing/instream_dissolved_nutrient.go
 * 
 * Don't edit this file. Edit ./models/routing/instream_dissolved_nutrient.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type InstreamDissolvedNutrientDecay struct {
  doDecay data.ND1Float64
  pointSourceLoad data.ND1Float64
  linkHeight data.ND1Float64
  linkWidth data.ND1Float64
  linkLength data.ND1Float64
  uptakeVelocity data.ND1Float64
  durationInSeconds data.ND1Float64
  

  
}

func (m *InstreamDissolvedNutrientDecay) ApplyParameters(parameters data.ND2Float64) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}

  m.doDecay = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.pointSourceLoad = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.linkHeight = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.linkWidth = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.linkLength = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.uptakeVelocity = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.durationInSeconds = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  
}


func buildInstreamDissolvedNutrientDecay() sim.TimeSteppingModel {
	result := InstreamDissolvedNutrientDecay{}
	return &result
}

func init() {
	sim.Catalog["InstreamDissolvedNutrientDecay"] = buildInstreamDissolvedNutrientDecay
}

func (m *InstreamDissolvedNutrientDecay)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  doDecayDims := []string{
      }
  
  pointSourceLoadDims := []string{
      }
  
  linkHeightDims := []string{
      }
  
  linkWidthDims := []string{
      }
  
  linkLengthDims := []string{
      }
  
  uptakeVelocityDims := []string{
      }
  
  durationInSecondsDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("doDecay",0,"",[]float64{ 0, 0 },"",doDecayDims),
  sim.DescribeParameter("pointSourceLoad",0,"",[]float64{ 0, 0 },"",pointSourceLoadDims),
  sim.DescribeParameter("linkHeight",0,"",[]float64{ 0, 0 },"",linkHeightDims),
  sim.DescribeParameter("linkWidth",0,"",[]float64{ 0, 0 },"",linkWidthDims),
  sim.DescribeParameter("linkLength",0,"",[]float64{ 0, 0 },"",linkLengthDims),
  sim.DescribeParameter("uptakeVelocity",0,"",[]float64{ 0, 0 },"",uptakeVelocityDims),
  sim.DescribeParameter("durationInSeconds",86400,"Timestep",[]float64{ 1, 86400 }," ",durationInSecondsDims),}

  result.Inputs = []string{
  "incomingMassUpstream","incomingMassLateral","reachVolume","outflow","floodplainDepositionFraction",}
  result.Outputs = []string{
  "decayedLoad","loadDownstream","loadToFloodplain","loadFromPointSource",}

  result.States = []string{
  "totalStoredMass",}

  result.Dimensions = []string{
      }
	return result
}

func (m *InstreamDissolvedNutrientDecay) InitialiseDimensions(dims []int) {
  
}

func (m *InstreamDissolvedNutrientDecay) FindDimensions(parameters data.ND2Float64) []int {
  
  return []int{}
  
}




func (m *InstreamDissolvedNutrientDecay) InitialiseStates(n int) data.ND2Float64 {
  // Zero states
	var result = data.NewArray2DFloat64(n,1)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,1)
  //   
	// 	stateSet[0] = 0 // totalStoredMass
  //   

  //   if result==nil {
  //     result = data.NewArray2DFloat64(stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *InstreamDissolvedNutrientDecay) Run(inputs data.ND3Float64, states data.ND2Float64, outputs data.ND3Float64) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3DFloat64( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running InstreamDissolvedNutrientDecay for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      dodecay := m.doDecay.Get1(i%m.doDecay.Len1())
      pointsourceload := m.pointSourceLoad.Get1(i%m.pointSourceLoad.Len1())
      linkheight := m.linkHeight.Get1(i%m.linkHeight.Len1())
      linkwidth := m.linkWidth.Get1(i%m.linkWidth.Len1())
      linklength := m.linkLength.Get1(i%m.linkLength.Len1())
      uptakevelocity := m.uptakeVelocity.Get1(i%m.uptakeVelocity.Len1())
      durationinseconds := m.durationInSeconds.Get1(i%m.durationInSeconds.Len1())
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).(data.ND1Float64)
      

      
      
      totalstoredmass := initialStates.Get1(0)
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{incomingMassUpstream <nil>}",tmpTS.Shape())
      incomingmassupstream := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{incomingMassLateral <nil>}",tmpTS.Shape())
      incomingmasslateral := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{reachVolume <nil>}",tmpTS.Shape())
      reachvolume := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{outflow <nil>}",tmpTS.Shape())
      outflow := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{floodplainDepositionFraction <nil>}",tmpTS.Shape())
      floodplaindepositionfraction := cellInputs.Slice([]int{ 4,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      decayedload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      loaddownstream := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      loadtofloodplain := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      loadfrompointsource := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      

      totalstoredmass= instreamDissolvedNutrient(incomingmassupstream,incomingmasslateral,reachvolume,outflow,floodplaindepositionfraction,totalstoredmass,dodecay,pointsourceload,linkheight,linkwidth,linklength,uptakevelocity,durationinseconds,decayedload,loaddownstream,loadtofloodplain,loadfrompointsource)

      
      
      initialStates.Set1(0, totalstoredmass)
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 4)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
