package rr

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/rr/surm.go
 * 
 * Don't edit this file. Edit models/rr/surm.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type Surm struct {
  
      bfac []float64
    
  
      coeff []float64
    
  
      dseep []float64
    
  
      fcFrac []float64
    
  
      fimp []float64
    
  
      rfac []float64
    
  
      smax []float64
    
  
      sq []float64
    
  
      thres []float64
    
  

  
}

func (m *Surm) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.bfac = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.coeff = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.dseep = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.fcFrac = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.fimp = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.rfac = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.smax = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.sq = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.thres = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildSurm() sim.TimeSteppingModel {
	result := Surm{}
	return &result
}

func init() {
	sim.Catalog["Surm"] = buildSurm
}

func (m *Surm)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  bfacDims := []string{
      }
  
  coeffDims := []string{
      }
  
  dseepDims := []string{
      }
  
  fcFracDims := []string{
      }
  
  fimpDims := []string{
      }
  
  rfacDims := []string{
      }
  
  smaxDims := []string{
      }
  
  sqDims := []string{
      }
  
  thresDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("bfac",0,"",[]float64{ 0, 0 },"",bfacDims),
  sim.DescribeParameter("coeff",0,"",[]float64{ 0, 0 },"",coeffDims),
  sim.DescribeParameter("dseep",0,"",[]float64{ 0, 0 },"",dseepDims),
  sim.DescribeParameter("fcFrac",0,"",[]float64{ 0, 0 },"",fcFracDims),
  sim.DescribeParameter("fimp",0,"",[]float64{ 0, 0 },"",fimpDims),
  sim.DescribeParameter("rfac",0,"",[]float64{ 0, 0 },"",rfacDims),
  sim.DescribeParameter("smax",0,"",[]float64{ 0, 0 },"",smaxDims),
  sim.DescribeParameter("sq",0,"",[]float64{ 0, 0 },"",sqDims),
  sim.DescribeParameter("thres",0,"",[]float64{ 0, 0 },"",thresDims),}

  result.Inputs = []string{
  "rainfall","pet",}
  result.Outputs = []string{
  "runoff","quickflow","baseflow","store",}

  result.States = []string{
  "SoilMoistureStore","Groundwater","TotalStore",}

  result.Dimensions = []string{
      }
	return result
}

func (m *Surm) InitialiseDimensions(dims []int) {
  
}

func (m *Surm) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *Surm) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,3)
	return result
}



func (m *Surm) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      bfac := m.bfac[i%len(m.bfac)]
      coeff := m.coeff[i%len(m.coeff)]
      dseep := m.dseep[i%len(m.dseep)]
      fcfrac := m.fcFrac[i%len(m.fcFrac)]
      fimp := m.fimp[i%len(m.fimp)]
      rfac := m.rfac[i%len(m.rfac)]
      smax := m.smax[i%len(m.smax)]
      sq := m.sq[i%len(m.sq)]
      thres := m.thres[i%len(m.thres)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      soilmoisturestore := initialStates[0]
      
      groundwater := initialStates[1]
      
      totalstore := initialStates[2]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      rainfall := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      pet := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      runoff := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      runoffSliced := runoff.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      quickflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      quickflowSliced := quickflow.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      baseflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      baseflowSliced := baseflow.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      store := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      storeSliced := store.Unroll()
      
      

      soilmoisturestore,groundwater,totalstore= surm(rainfall,pet,soilmoisturestore,groundwater,totalstore,bfac,coeff,dseep,fcfrac,fimp,rfac,smax,sq,thres,runoffSliced,quickflowSliced,baseflowSliced,storeSliced)

      
      
      runoff.Reroll()
      
      quickflow.Reroll()
      
      baseflow.Reroll()
      
      store.Reroll()
      
      

      
      
      initialStates[0] = soilmoisturestore
      
      initialStates[1] = groundwater
      
      initialStates[2] = totalstore
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
