package rr

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/rr/sacramento.go
 * 
 * Don't edit this file. Edit models/rr/sacramento.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type Sacramento struct {
  
      lzpk []float64
    
  
      lzsk []float64
    
  
      uzk []float64
    
  
      uztwm []float64
    
  
      uzfwm []float64
    
  
      lztwm []float64
    
  
      lzfsm []float64
    
  
      lzfpm []float64
    
  
      pfree []float64
    
  
      rexp []float64
    
  
      zperc []float64
    
  
      side []float64
    
  
      ssout []float64
    
  
      pctim []float64
    
  
      adimp []float64
    
  
      sarva []float64
    
  
      rserv []float64
    
  
      uh1 []float64
    
  
      uh2 []float64
    
  
      uh3 []float64
    
  
      uh4 []float64
    
  
      uh5 []float64
    
  

  
}

func (m *Sacramento) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.lzpk = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.lzsk = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uzk = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uztwm = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uzfwm = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.lztwm = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.lzfsm = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.lzfpm = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.pfree = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.rexp = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.zperc = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.side = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.ssout = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.pctim = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.adimp = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.sarva = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.rserv = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uh1 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uh2 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uh3 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uh4 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.uh5 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildSacramento() sim.TimeSteppingModel {
	result := Sacramento{}
	return &result
}

func init() {
	sim.Catalog["Sacramento"] = buildSacramento
}

func (m *Sacramento)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  lzpkDims := []string{
      }
  
  lzskDims := []string{
      }
  
  uzkDims := []string{
      }
  
  uztwmDims := []string{
      }
  
  uzfwmDims := []string{
      }
  
  lztwmDims := []string{
      }
  
  lzfsmDims := []string{
      }
  
  lzfpmDims := []string{
      }
  
  pfreeDims := []string{
      }
  
  rexpDims := []string{
      }
  
  zpercDims := []string{
      }
  
  sideDims := []string{
      }
  
  ssoutDims := []string{
      }
  
  pctimDims := []string{
      }
  
  adimpDims := []string{
      }
  
  sarvaDims := []string{
      }
  
  rservDims := []string{
      }
  
  uh1Dims := []string{
      }
  
  uh2Dims := []string{
      }
  
  uh3Dims := []string{
      }
  
  uh4Dims := []string{
      }
  
  uh5Dims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("lzpk",0.01,"Lower zone Primary Free water base flow ratio",[]float64{ 0, 1 }," ",lzpkDims),
  sim.DescribeParameter("lzsk",0.05,"Lower zone Supplementary Free water base flow ratio",[]float64{ 0, 1 }," ",lzskDims),
  sim.DescribeParameter("uzk",0.3,"Upper zone free water interflow fraction",[]float64{ 0, 1 }," ",uzkDims),
  sim.DescribeParameter("uztwm",50,"mm Upper zone tension water maximum",[]float64{ 0.1, 125 },"",uztwmDims),
  sim.DescribeParameter("uzfwm",40,"mm Upper zone free water maximum",[]float64{ 0, 75 },"",uzfwmDims),
  sim.DescribeParameter("lztwm",130,"mm Lower zone tension water maximum",[]float64{ 0, 300 },"",lztwmDims),
  sim.DescribeParameter("lzfsm",25,"mm Lower zone free water supplemental maximum",[]float64{ 0, 300 },"",lzfsmDims),
  sim.DescribeParameter("lzfpm",60,"mm Lower zone free water primary maximum",[]float64{ 0, 600 },"",lzfpmDims),
  sim.DescribeParameter("pfree",0.06,"Minimum proportion of percolation from upper zone to lower zone directly available for recharing lower zone free water stores.",[]float64{ 0, 1 }," ",pfreeDims),
  sim.DescribeParameter("rexp",1,"Exponent of rate of change of percolation rate with changing LZ storage",[]float64{ 0, 3 }," ",rexpDims),
  sim.DescribeParameter("zperc",40,"Proportional increase in Pbase defining maximum percolation rate",[]float64{ 0, 80 }," ",zpercDims),
  sim.DescribeParameter("side",0,"Ratio of non-channel baseflow to channel baseflow",[]float64{ 0, 1 }," ",sideDims),
  sim.DescribeParameter("ssout",0,"[0",[]float64{ 0, 0 },"",ssoutDims),
  sim.DescribeParameter("pctim",0.01,"fraction of catchment that is permanently and directly connected impervious",[]float64{ 0, 1 }," ",pctimDims),
  sim.DescribeParameter("adimp",0,"additional fraction of catchment that can act impervious under saturated soil conditions.",[]float64{ 0, 1 }," ",adimpDims),
  sim.DescribeParameter("sarva",0,"fraction of basin normally covered by streams",[]float64{ 0, 1 }," ",sarvaDims),
  sim.DescribeParameter("rserv",0.3,"Fraction lower zone free water that is not available for transpiration",[]float64{ 0, 1 }," ",rservDims),
  sim.DescribeParameter("uh1",0.8,"Unit hydrograph - proportion runoff that is instantaneous",[]float64{ 0, 1 }," ",uh1Dims),
  sim.DescribeParameter("uh2",0.1,"Unit hydrograph - proportion lagged by one timestep",[]float64{ 0, 1 }," ",uh2Dims),
  sim.DescribeParameter("uh3",0.05,"Unit hydrograph - proportion lagged by two timesteps",[]float64{ 0, 1 }," ",uh3Dims),
  sim.DescribeParameter("uh4",0.03,"Unit hydrograph - proportion lagged by three timesteps",[]float64{ 0, 1 }," ",uh4Dims),
  sim.DescribeParameter("uh5",0.02,"Unit hydrograph - proportion lagged by four timesteps",[]float64{ 0, 1 }," ",uh5Dims),}

  result.Inputs = []string{
  "rainfall","pet",}
  result.Outputs = []string{
  "actualET","runoff","imperviousRunoff","surfaceRunoff","baseflow",}

  result.States = []string{
  "UprTensionWater","UprFreeWater","LwrTensionWater","LwrPrimaryFreeWater","LwrSupplFreeWater","AdditionalImperviousStore",}

  result.Dimensions = []string{
      }
	return result
}

func (m *Sacramento) InitialiseDimensions(dims []int) {
  
}

func (m *Sacramento) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *Sacramento) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,6)
	return result
}



func (m *Sacramento) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 5, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      lzpk := m.lzpk[i%len(m.lzpk)]
      lzsk := m.lzsk[i%len(m.lzsk)]
      uzk := m.uzk[i%len(m.uzk)]
      uztwm := m.uztwm[i%len(m.uztwm)]
      uzfwm := m.uzfwm[i%len(m.uzfwm)]
      lztwm := m.lztwm[i%len(m.lztwm)]
      lzfsm := m.lzfsm[i%len(m.lzfsm)]
      lzfpm := m.lzfpm[i%len(m.lzfpm)]
      pfree := m.pfree[i%len(m.pfree)]
      rexp := m.rexp[i%len(m.rexp)]
      zperc := m.zperc[i%len(m.zperc)]
      side := m.side[i%len(m.side)]
      ssout := m.ssout[i%len(m.ssout)]
      pctim := m.pctim[i%len(m.pctim)]
      adimp := m.adimp[i%len(m.adimp)]
      sarva := m.sarva[i%len(m.sarva)]
      rserv := m.rserv[i%len(m.rserv)]
      uh1 := m.uh1[i%len(m.uh1)]
      uh2 := m.uh2[i%len(m.uh2)]
      uh3 := m.uh3[i%len(m.uh3)]
      uh4 := m.uh4[i%len(m.uh4)]
      uh5 := m.uh5[i%len(m.uh5)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      uprtensionwater := initialStates[0]
      
      uprfreewater := initialStates[1]
      
      lwrtensionwater := initialStates[2]
      
      lwrprimaryfreewater := initialStates[3]
      
      lwrsupplfreewater := initialStates[4]
      
      additionalimperviousstore := initialStates[5]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      rainfall := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      pet := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      actualet := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      actualetSliced := actualet.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      runoff := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      runoffSliced := runoff.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      imperviousrunoff := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      imperviousrunoffSliced := imperviousrunoff.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      surfacerunoff := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      surfacerunoffSliced := surfacerunoff.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 4
      baseflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      baseflowSliced := baseflow.Unroll()
      
      

      uprtensionwater,uprfreewater,lwrtensionwater,lwrprimaryfreewater,lwrsupplfreewater,additionalimperviousstore= sacramento(rainfall,pet,uprtensionwater,uprfreewater,lwrtensionwater,lwrprimaryfreewater,lwrsupplfreewater,additionalimperviousstore,lzpk,lzsk,uzk,uztwm,uzfwm,lztwm,lzfsm,lzfpm,pfree,rexp,zperc,side,ssout,pctim,adimp,sarva,rserv,uh1,uh2,uh3,uh4,uh5,actualetSliced,runoffSliced,imperviousrunoffSliced,surfacerunoffSliced,baseflowSliced)

      
      
      actualet.Reroll()
      
      runoff.Reroll()
      
      imperviousrunoff.Reroll()
      
      surfacerunoff.Reroll()
      
      baseflow.Reroll()
      
      

      
      
      initialStates[0] = uprtensionwater
      
      initialStates[1] = uprfreewater
      
      initialStates[2] = lwrtensionwater
      
      initialStates[3] = lwrprimaryfreewater
      
      initialStates[4] = lwrsupplfreewater
      
      initialStates[5] = additionalimperviousstore
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
