package rr

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/rr/simhyd.go
 * 
 * Don't edit this file. Edit models/rr/simhyd.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type Simhyd struct {
  
      baseflowCoefficient []float64
    
  
      imperviousThreshold []float64
    
  
      infiltrationCoefficient []float64
    
  
      infiltrationShape []float64
    
  
      interflowCoefficient []float64
    
  
      perviousFraction []float64
    
  
      rainfallInterceptionStoreCapacity []float64
    
  
      rechargeCoefficient []float64
    
  
      soilMoistureStoreCapacity []float64
    
  

  
}

func (m *Simhyd) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.baseflowCoefficient = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.imperviousThreshold = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.infiltrationCoefficient = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.infiltrationShape = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.interflowCoefficient = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.perviousFraction = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.rainfallInterceptionStoreCapacity = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.rechargeCoefficient = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.soilMoistureStoreCapacity = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildSimhyd() sim.TimeSteppingModel {
	result := Simhyd{}
	return &result
}

func init() {
	sim.Catalog["Simhyd"] = buildSimhyd
}

func (m *Simhyd)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  baseflowCoefficientDims := []string{
      }
  
  imperviousThresholdDims := []string{
      }
  
  infiltrationCoefficientDims := []string{
      }
  
  infiltrationShapeDims := []string{
      }
  
  interflowCoefficientDims := []string{
      }
  
  perviousFractionDims := []string{
      }
  
  rainfallInterceptionStoreCapacityDims := []string{
      }
  
  rechargeCoefficientDims := []string{
      }
  
  soilMoistureStoreCapacityDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("baseflowCoefficient",0,"",[]float64{ 0, 0 },"",baseflowCoefficientDims),
  sim.DescribeParameter("imperviousThreshold",0,"",[]float64{ 0, 0 },"",imperviousThresholdDims),
  sim.DescribeParameter("infiltrationCoefficient",0,"",[]float64{ 0, 0 },"",infiltrationCoefficientDims),
  sim.DescribeParameter("infiltrationShape",0,"",[]float64{ 0, 0 },"",infiltrationShapeDims),
  sim.DescribeParameter("interflowCoefficient",0,"",[]float64{ 0, 0 },"",interflowCoefficientDims),
  sim.DescribeParameter("perviousFraction",0,"",[]float64{ 0, 0 },"",perviousFractionDims),
  sim.DescribeParameter("rainfallInterceptionStoreCapacity",0,"",[]float64{ 0, 0 },"",rainfallInterceptionStoreCapacityDims),
  sim.DescribeParameter("rechargeCoefficient",0,"",[]float64{ 0, 0 },"",rechargeCoefficientDims),
  sim.DescribeParameter("soilMoistureStoreCapacity",0,"",[]float64{ 0, 0 },"",soilMoistureStoreCapacityDims),}

  result.Inputs = []string{
  "rainfall","pet",}
  result.Outputs = []string{
  "runoff","quickflow","baseflow","store",}

  result.States = []string{
  "SoilMoistureStore","Groundwater","TotalStore",}

  result.Dimensions = []string{
      }
	return result
}

func (m *Simhyd) InitialiseDimensions(dims []int) {
  
}

func (m *Simhyd) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *Simhyd) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,3)
	return result
}



func (m *Simhyd) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      baseflowcoefficient := m.baseflowCoefficient[i%len(m.baseflowCoefficient)]
      imperviousthreshold := m.imperviousThreshold[i%len(m.imperviousThreshold)]
      infiltrationcoefficient := m.infiltrationCoefficient[i%len(m.infiltrationCoefficient)]
      infiltrationshape := m.infiltrationShape[i%len(m.infiltrationShape)]
      interflowcoefficient := m.interflowCoefficient[i%len(m.interflowCoefficient)]
      perviousfraction := m.perviousFraction[i%len(m.perviousFraction)]
      rainfallinterceptionstorecapacity := m.rainfallInterceptionStoreCapacity[i%len(m.rainfallInterceptionStoreCapacity)]
      rechargecoefficient := m.rechargeCoefficient[i%len(m.rechargeCoefficient)]
      soilmoisturestorecapacity := m.soilMoistureStoreCapacity[i%len(m.soilMoistureStoreCapacity)]
      

      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).Unroll()
      

      
      
      soilmoisturestore := initialStates[0]
      
      groundwater := initialStates[1]
      
      totalstore := initialStates[2]
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      rainfall := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      pet := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      runoff := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      runoffSliced := runoff.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      quickflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      quickflowSliced := quickflow.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      baseflow := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      baseflowSliced := baseflow.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      store := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      storeSliced := store.Unroll()
      
      

      soilmoisturestore,groundwater,totalstore= simhyd(rainfall,pet,soilmoisturestore,groundwater,totalstore,baseflowcoefficient,imperviousthreshold,infiltrationcoefficient,infiltrationshape,interflowcoefficient,perviousfraction,rainfallinterceptionstorecapacity,rechargecoefficient,soilmoisturestorecapacity,runoffSliced,quickflowSliced,baseflowSliced,storeSliced)

      
      
      runoff.Reroll()
      
      quickflow.Reroll()
      
      baseflow.Reroll()
      
      store.Reroll()
      
      

      
      
      initialStates[0] = soilmoisturestore
      
      initialStates[1] = groundwater
      
      initialStates[2] = totalstore
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
