// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package m

func MinFloat32(a, b float32) float32 {
	if a > b {
		return b
	}

	return a
}

func MaxFloat32(a, b float32) float32 {
	if a > b {
		return a
	}

	return b
}

func MinFloat64(a, b float64) float64 {
	if a > b {
		return b
	}

	return a
}

func MaxFloat64(a, b float64) float64 {
	if a > b {
		return a
	}

	return b
}

func MinInt(a, b int) int {
	if a > b {
		return b
	}

	return a
}

func MaxInt(a, b int) int {
	if a > b {
		return a
	}

	return b
}

func MinInt16(a, b int16) int16 {
	if a > b {
		return b
	}

	return a
}

func MaxInt16(a, b int16) int16 {
	if a > b {
		return a
	}

	return b
}

func MinInt32(a, b int32) int32 {
	if a > b {
		return b
	}

	return a
}

func MaxInt32(a, b int32) int32 {
	if a > b {
		return a
	}

	return b
}

func MinInt64(a, b int64) int64 {
	if a > b {
		return b
	}

	return a
}

func MaxInt64(a, b int64) int64 {
	if a > b {
		return a
	}

	return b
}

func MinInt8(a, b int8) int8 {
	if a > b {
		return b
	}

	return a
}

func MaxInt8(a, b int8) int8 {
	if a > b {
		return a
	}

	return b
}

func MinUint(a, b uint) uint {
	if a > b {
		return b
	}

	return a
}

func MaxUint(a, b uint) uint {
	if a > b {
		return a
	}

	return b
}

func MinUint16(a, b uint16) uint16 {
	if a > b {
		return b
	}

	return a
}

func MaxUint16(a, b uint16) uint16 {
	if a > b {
		return a
	}

	return b
}

func MinUint32(a, b uint32) uint32 {
	if a > b {
		return b
	}

	return a
}

func MaxUint32(a, b uint32) uint32 {
	if a > b {
		return a
	}

	return b
}

func MinUint64(a, b uint64) uint64 {
	if a > b {
		return b
	}

	return a
}

func MaxUint64(a, b uint64) uint64 {
	if a > b {
		return a
	}

	return b
}

func MinUint8(a, b uint8) uint8 {
	if a > b {
		return b
	}

	return a
}

func MaxUint8(a, b uint8) uint8 {
	if a > b {
		return a
	}

	return b
}
