package storage

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from ./models/storage/sediment_trapping.go
 * 
 * Don't edit this file. Edit ./models/storage/sediment_trapping.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type StorageParticulateTrapping struct {
  DeltaT data.ND1Float64
  reservoirCapacity data.ND1Float64
  reservoirLength data.ND1Float64
  subtractor data.ND1Float64
  multiplier data.ND1Float64
  lengthDischargeFactor data.ND1Float64
  lengthDischargePower data.ND1Float64
  

  
}

func (m *StorageParticulateTrapping) ApplyParameters(parameters data.ND2Float64) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}

  m.DeltaT = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.reservoirCapacity = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.reservoirLength = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.subtractor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.multiplier = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.lengthDischargeFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.lengthDischargePower = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  
}


func buildStorageParticulateTrapping() sim.TimeSteppingModel {
	result := StorageParticulateTrapping{}
	return &result
}

func init() {
	sim.Catalog["StorageParticulateTrapping"] = buildStorageParticulateTrapping
}

func (m *StorageParticulateTrapping)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  DeltaTDims := []string{
      }
  
  reservoirCapacityDims := []string{
      }
  
  reservoirLengthDims := []string{
      }
  
  subtractorDims := []string{
      }
  
  multiplierDims := []string{
      }
  
  lengthDischargeFactorDims := []string{
      }
  
  lengthDischargePowerDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("DeltaT",86400,"Timestep",[]float64{ 1, 86400 }," ",DeltaTDims),
  sim.DescribeParameter("reservoirCapacity",0,"",[]float64{ 0, 0 },"",reservoirCapacityDims),
  sim.DescribeParameter("reservoirLength",0,"Length (m) of reservoir from dam wall to longest impounded water at dam capacity",[]float64{ 0, 0 },"",reservoirLengthDims),
  sim.DescribeParameter("subtractor",0,"default=112",[]float64{ 0, 0 },"",subtractorDims),
  sim.DescribeParameter("multiplier",0,"default=800",[]float64{ 0, 0 },"",multiplierDims),
  sim.DescribeParameter("lengthDischargeFactor",0,"",[]float64{ 0, 0 },"",lengthDischargeFactorDims),
  sim.DescribeParameter("lengthDischargePower",0,"",[]float64{ 0, 0 },"",lengthDischargePowerDims),}

  result.Inputs = []string{
  "inflowLoad","inflow","outflow","storage",}
  result.Outputs = []string{
  "trappedMass","outflowLoad",}

  result.States = []string{
  "storedMass",}

  result.Dimensions = []string{
      }
	return result
}

func (m *StorageParticulateTrapping) InitialiseDimensions(dims []int) {
  
}

func (m *StorageParticulateTrapping) FindDimensions(parameters data.ND2Float64) []int {
  
  return []int{}
  
}




func (m *StorageParticulateTrapping) InitialiseStates(n int) data.ND2Float64 {
  // Zero states
	var result = data.NewArray2DFloat64(n,1)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,1)
  //   
	// 	stateSet[0] = 0 // storedMass
  //   

  //   if result==nil {
  //     result = data.NewArray2DFloat64(stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *StorageParticulateTrapping) Run(inputs data.ND3Float64, states data.ND2Float64, outputs data.ND3Float64) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3DFloat64( 2, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running StorageParticulateTrapping for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      deltat := m.DeltaT.Get1(i%m.DeltaT.Len1())
      reservoircapacity := m.reservoirCapacity.Get1(i%m.reservoirCapacity.Len1())
      reservoirlength := m.reservoirLength.Get1(i%m.reservoirLength.Len1())
      subtractor := m.subtractor.Get1(i%m.subtractor.Len1())
      multiplier := m.multiplier.Get1(i%m.multiplier.Len1())
      lengthdischargefactor := m.lengthDischargeFactor.Get1(i%m.lengthDischargeFactor.Len1())
      lengthdischargepower := m.lengthDischargePower.Get1(i%m.lengthDischargePower.Len1())
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      
      initialStates := states.Slice(statesPosSlice,statesSizeSlice,nil).MustReshape([]int{numStates}).(data.ND1Float64)
      

      
      
      storedmass := initialStates.Get1(0)
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{inflowLoad kg.s^-1}",tmpTS.Shape())
      inflowload := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{inflow m^3.s^-1}",tmpTS.Shape())
      inflow := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{outflow m^3.s^-1}",tmpTS.Shape())
      outflow := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{storage m^3}",tmpTS.Shape())
      storage := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      trappedmass := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      outflowload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      

      storedmass= storageParticulateTrapping(inflowload,inflow,outflow,storage,storedmass,deltat,reservoircapacity,reservoirlength,subtractor,multiplier,lengthdischargefactor,lengthdischargepower,trappedmass,outflowload)

      
      
      initialStates.Set1(0, storedmass)
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 2)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
