package generation

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/generation/particulate_nutrients.go
 * 
 * Don't edit this file. Edit models/generation/particulate_nutrients.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type SednetParticulateNutrientGeneration struct {
  
      area []float64
    
  
      nutSurfSoilConc []float64
    
  
      hillDeliveryRatio []float64
    
  
      Nutrient_Enrichment_Ratio []float64
    
  
      nutSubSoilConc []float64
    
  
      Nutrient_Enrichment_Ratio_Gully []float64
    
  
      gullyDeliveryRatio []float64
    
  
      nutrientDWC []float64
    
  
      Do_P_CREAMS_Enrichment []float64
    
  

  
}

func (m *SednetParticulateNutrientGeneration) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.area = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.nutSurfSoilConc = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.hillDeliveryRatio = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.Nutrient_Enrichment_Ratio = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.nutSubSoilConc = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.Nutrient_Enrichment_Ratio_Gully = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.gullyDeliveryRatio = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.nutrientDWC = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.Do_P_CREAMS_Enrichment = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildSednetParticulateNutrientGeneration() sim.TimeSteppingModel {
	result := SednetParticulateNutrientGeneration{}
	return &result
}

func init() {
	sim.Catalog["SednetParticulateNutrientGeneration"] = buildSednetParticulateNutrientGeneration
}

func (m *SednetParticulateNutrientGeneration)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  areaDims := []string{
      }
  
  nutSurfSoilConcDims := []string{
      }
  
  hillDeliveryRatioDims := []string{
      }
  
  Nutrient_Enrichment_RatioDims := []string{
      }
  
  nutSubSoilConcDims := []string{
      }
  
  Nutrient_Enrichment_Ratio_GullyDims := []string{
      }
  
  gullyDeliveryRatioDims := []string{
      }
  
  nutrientDWCDims := []string{
      }
  
  Do_P_CREAMS_EnrichmentDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("area",0,"m^2",[]float64{ 0, 0 },"",areaDims),
  sim.DescribeParameter("nutSurfSoilConc",0,"kg.kg^-1",[]float64{ 0, 0 },"",nutSurfSoilConcDims),
  sim.DescribeParameter("hillDeliveryRatio",0,"%",[]float64{ 0, 0 },"",hillDeliveryRatioDims),
  sim.DescribeParameter("Nutrient_Enrichment_Ratio",0,"",[]float64{ 0, 0 },"",Nutrient_Enrichment_RatioDims),
  sim.DescribeParameter("nutSubSoilConc",0,"kg.kg^-1",[]float64{ 0, 0 },"",nutSubSoilConcDims),
  sim.DescribeParameter("Nutrient_Enrichment_Ratio_Gully",0,"",[]float64{ 0, 0 },"",Nutrient_Enrichment_Ratio_GullyDims),
  sim.DescribeParameter("gullyDeliveryRatio",0,"%",[]float64{ 0, 0 },"",gullyDeliveryRatioDims),
  sim.DescribeParameter("nutrientDWC",0,"mg.L^-1",[]float64{ 0, 0 },"",nutrientDWCDims),
  sim.DescribeParameter("Do_P_CREAMS_Enrichment",0,"flag",[]float64{ 0, 0 },"",Do_P_CREAMS_EnrichmentDims),}

  result.Inputs = []string{
  "fineSedModelFineSheetGeneratedKg","fineSedModelCoarseSheetGeneratedKg","fineSedModelFineGullyGeneratedKg","fineSedModelCoarseGullyGeneratedKg","slowflow",}
  result.Outputs = []string{
  "quickflowConstituent","slowflowConstituent","totalLoad","hillslopeContribution","gullyContribution",}

  result.States = []string{
  }

  result.Dimensions = []string{
      }
	return result
}

func (m *SednetParticulateNutrientGeneration) InitialiseDimensions(dims []int) {
  
}

func (m *SednetParticulateNutrientGeneration) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *SednetParticulateNutrientGeneration) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,0)
	return result
}



func (m *SednetParticulateNutrientGeneration) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 5, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      area := m.area[i%len(m.area)]
      nutsurfsoilconc := m.nutSurfSoilConc[i%len(m.nutSurfSoilConc)]
      hilldeliveryratio := m.hillDeliveryRatio[i%len(m.hillDeliveryRatio)]
      nutrient_enrichment_ratio := m.Nutrient_Enrichment_Ratio[i%len(m.Nutrient_Enrichment_Ratio)]
      nutsubsoilconc := m.nutSubSoilConc[i%len(m.nutSubSoilConc)]
      nutrient_enrichment_ratio_gully := m.Nutrient_Enrichment_Ratio_Gully[i%len(m.Nutrient_Enrichment_Ratio_Gully)]
      gullydeliveryratio := m.gullyDeliveryRatio[i%len(m.gullyDeliveryRatio)]
      nutrientdwc := m.nutrientDWC[i%len(m.nutrientDWC)]
      do_p_creams_enrichment := m.Do_P_CREAMS_Enrichment[i%len(m.Do_P_CREAMS_Enrichment)]
      

      

      
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      finesedmodelfinesheetgeneratedkg := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      finesedmodelcoarsesheetgeneratedkg := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      finesedmodelfinegullygeneratedkg := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      finesedmodelcoarsegullygeneratedkg := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      slowflow := cellInputs.Slice([]int{ 4,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      quickflowconstituent := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      quickflowconstituentSliced := quickflowconstituent.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      slowflowconstituent := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      slowflowconstituentSliced := slowflowconstituent.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      totalload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      totalloadSliced := totalload.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      hillslopecontribution := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      hillslopecontributionSliced := hillslopecontribution.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 4
      gullycontribution := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      gullycontributionSliced := gullycontribution.Unroll()
      
      

       particulateNutrients(finesedmodelfinesheetgeneratedkg,finesedmodelcoarsesheetgeneratedkg,finesedmodelfinegullygeneratedkg,finesedmodelcoarsegullygeneratedkg,slowflow,area,nutsurfsoilconc,hilldeliveryratio,nutrient_enrichment_ratio,nutsubsoilconc,nutrient_enrichment_ratio_gully,gullydeliveryratio,nutrientdwc,do_p_creams_enrichment,quickflowconstituentSliced,slowflowconstituentSliced,totalloadSliced,hillslopecontributionSliced,gullycontributionSliced)

      
      
      quickflowconstituent.Reroll()
      
      slowflowconstituent.Reroll()
      
      totalload.Reroll()
      
      hillslopecontribution.Reroll()
      
      gullycontribution.Reroll()
      
      

      
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
