package generation

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from ./models/generation/muslefine.go
 * 
 * Don't edit this file. Edit ./models/generation/muslefine.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type MUSLEEventBasedRFactor struct {
  alpha data.ND1Float64
  eta data.ND1Float64
  scalingFactor data.ND1Float64
  a data.ND1Float64
  b1 data.ND1Float64
  b2 data.ND1Float64
  timeStepInSeconds data.ND1Float64
  

  
}

func (m *MUSLEEventBasedRFactor) ApplyParameters(parameters data.ND2Float64) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}

  m.alpha = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.eta = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.scalingFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.a = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.b1 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.b2 = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}

  m.timeStepInSeconds = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1Float64)
  paramIdx += paramSize

  
}


func buildMUSLEEventBasedRFactor() sim.TimeSteppingModel {
	result := MUSLEEventBasedRFactor{}
	return &result
}

func init() {
	sim.Catalog["MUSLEEventBasedRFactor"] = buildMUSLEEventBasedRFactor
}

func (m *MUSLEEventBasedRFactor)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  alphaDims := []string{
      }
  
  etaDims := []string{
      }
  
  scalingFactorDims := []string{
      }
  
  aDims := []string{
      }
  
  b1Dims := []string{
      }
  
  b2Dims := []string{
      }
  
  timeStepInSecondsDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("alpha",0.75155,"unitless",[]float64{ 0, 0 },"",alphaDims),
  sim.DescribeParameter("eta",0.29,"unitless",[]float64{ 0, 0 },"",etaDims),
  sim.DescribeParameter("scalingFactor",0.0609,"unitless",[]float64{ 0, 0 },"",scalingFactorDims),
  sim.DescribeParameter("a",89.45,"unitless",[]float64{ 0, 0 },"",aDims),
  sim.DescribeParameter("b1",0.56,"unitless",[]float64{ 0, 0 },"",b1Dims),
  sim.DescribeParameter("b2",0.56,"unitless",[]float64{ 0, 0 },"",b2Dims),
  sim.DescribeParameter("timeStepInSeconds",86400,"s Duration of timestep in seconds",[]float64{ 0, 1e+08 },"",timeStepInSecondsDims),}

  result.Inputs = []string{
  "rainfall","totalFlow","month",}
  result.Outputs = []string{
  "R","debugInEvent",}

  result.States = []string{
  }

  result.Dimensions = []string{
      }
	return result
}

func (m *MUSLEEventBasedRFactor) InitialiseDimensions(dims []int) {
  
}

func (m *MUSLEEventBasedRFactor) FindDimensions(parameters data.ND2Float64) []int {
  
  return []int{}
  
}




func (m *MUSLEEventBasedRFactor) InitialiseStates(n int) data.ND2Float64 {
  // Zero states
	var result = data.NewArray2DFloat64(n,0)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,0)
  //   

  //   if result==nil {
  //     result = data.NewArray2DFloat64(stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *MUSLEEventBasedRFactor) Run(inputs data.ND3Float64, states data.ND2Float64, outputs data.ND3Float64) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3DFloat64( 2, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running MUSLEEventBasedRFactor for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      alpha := m.alpha.Get1(i%m.alpha.Len1())
      eta := m.eta.Get1(i%m.eta.Len1())
      scalingfactor := m.scalingFactor.Get1(i%m.scalingFactor.Len1())
      a := m.a.Get1(i%m.a.Len1())
      b1 := m.b1.Get1(i%m.b1.Len1())
      b2 := m.b2.Get1(i%m.b2.Len1())
      timestepinseconds := m.timeStepInSeconds.Get1(i%m.timeStepInSeconds.Len1())
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      

      
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{rainfall mm.day^-1}",tmpTS.Shape())
      rainfall := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{totalFlow mm.day^-1}",tmpTS.Shape())
      totalflow := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      
  //    fmt.Println("{month <nil>}",tmpTS.Shape())
      month := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).(data.ND1Float64)
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      r := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      debuginevent := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).(data.ND1Float64)
      
      

       musleEventBasedRFactor(rainfall,totalflow,month,alpha,eta,scalingfactor,a,b1,b2,timestepinseconds,r,debuginevent)

      
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 2)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
