package generation

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/generation/dissolved_nutrients.go
 * 
 * Don't edit this file. Edit models/generation/dissolved_nutrients.go instead!
 */
import (
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type SednetDissolvedNutrientGeneration struct {
  
      dissConst_EMC []float64
    
  
      dissConst_DWC []float64
    
  

  
}

func (m *SednetDissolvedNutrientGeneration) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.dissConst_EMC = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.dissConst_DWC = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildSednetDissolvedNutrientGeneration() sim.TimeSteppingModel {
	result := SednetDissolvedNutrientGeneration{}
	return &result
}

func init() {
	sim.Catalog["SednetDissolvedNutrientGeneration"] = buildSednetDissolvedNutrientGeneration
}

func (m *SednetDissolvedNutrientGeneration)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  dissConst_EMCDims := []string{
      }
  
  dissConst_DWCDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("dissConst_EMC",0,"mg.L^-1",[]float64{ 0, 0 },"",dissConst_EMCDims),
  sim.DescribeParameter("dissConst_DWC",0,"mg.L^-1",[]float64{ 0, 0 },"",dissConst_DWCDims),}

  result.Inputs = []string{
  "quickflow","slowflow",}
  result.Outputs = []string{
  "quickflowConstituent","slowflowConstituent","totalLoad",}

  result.States = []string{
  }

  result.Dimensions = []string{
      }
	return result
}

func (m *SednetDissolvedNutrientGeneration) InitialiseDimensions(dims []int) {
  
}

func (m *SednetDissolvedNutrientGeneration) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *SednetDissolvedNutrientGeneration) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,0)
	return result
}



func (m *SednetDissolvedNutrientGeneration) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 3, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      dissconst_emc := m.dissConst_EMC[i%len(m.dissConst_EMC)]
      dissconst_dwc := m.dissConst_DWC[i%len(m.dissConst_DWC)]
      

      

      
      
      


      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
      
      quickflow := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
      slowflow := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      quickflowconstituent := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      quickflowconstituentSliced := quickflowconstituent.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      slowflowconstituent := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      slowflowconstituentSliced := slowflowconstituent.Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      totalload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen})
      totalloadSliced := totalload.Unroll()
      
      

       dissolvedNutrients(quickflow,slowflow,dissconst_emc,dissconst_dwc,quickflowconstituentSliced,slowflowconstituentSliced,totalloadSliced)

      
      
      quickflowconstituent.Reroll()
      
      slowflowconstituent.Reroll()
      
      totalload.Reroll()
      
      

      
      
      

      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
}
