package generation

/* WARNING: GENERATED CODE
 *
 * This file is generated by ow-specgen using metadata from models/generation/sednet_gully.go
 * 
 * Don't edit this file. Edit models/generation/sednet_gully.go instead!
 */
import (
//  "fmt"
  "github.com/flowmatters/openwater-core/sim"
  "github.com/flowmatters/openwater-core/data"
)


type DynamicSednetGully struct {
  
      YearDisturbance []float64
    
  
      GullyEndYear []float64
    
  
      Area []float64
    
  
      averageGullyActivityFactor []float64
    
  
      GullyAnnualAverageSedimentSupply []float64
    
  
      GullyPercentFine []float64
    
  
      managementPracticeFactor []float64
    
  
      longtermRunoffFactor []float64
    
  
      dailyRunoffPowerFactor []float64
    
  
      sdrFine []float64
    
  
      sdrCoarse []float64
    
  
      timeStepInSeconds []float64
    
  

  
}

func (m *DynamicSednetGully) ApplyParameters(parameters data.ND2[float64]) {

  nSets := parameters.Len(sim.DIMP_CELL)
  var newShape []int
  paramIdx := 0
  paramSize := 1


  paramSize = 1
  newShape = []int{ nSets}
  
    m.YearDisturbance = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.GullyEndYear = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.Area = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.averageGullyActivityFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.GullyAnnualAverageSedimentSupply = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.GullyPercentFine = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.managementPracticeFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.longtermRunoffFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.dailyRunoffPowerFactor = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.sdrFine = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.sdrCoarse = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  paramSize = 1
  newShape = []int{ nSets}
  
    m.timeStepInSeconds = parameters.Slice([]int{ paramIdx, 0}, []int{ paramSize, nSets}, nil).MustReshape(newShape).(data.ND1[float64]).Unroll()
  
  paramIdx += paramSize

  
}


func buildDynamicSednetGully() sim.TimeSteppingModel {
	result := DynamicSednetGully{}
	return &result
}

func init() {
	sim.Catalog["DynamicSednetGully"] = buildDynamicSednetGully
}

func (m *DynamicSednetGully)  Description() sim.ModelDescription{
	var result sim.ModelDescription
  
  YearDisturbanceDims := []string{
      }
  
  GullyEndYearDims := []string{
      }
  
  AreaDims := []string{
      }
  
  averageGullyActivityFactorDims := []string{
      }
  
  GullyAnnualAverageSedimentSupplyDims := []string{
      }
  
  GullyPercentFineDims := []string{
      }
  
  managementPracticeFactorDims := []string{
      }
  
  longtermRunoffFactorDims := []string{
      }
  
  dailyRunoffPowerFactorDims := []string{
      }
  
  sdrFineDims := []string{
      }
  
  sdrCoarseDims := []string{
      }
  
  timeStepInSecondsDims := []string{
      }
  
	result.Parameters = []sim.ParameterDescription{
  
  sim.DescribeParameter("YearDisturbance",0,"",[]float64{ 0, 0 },"",YearDisturbanceDims),
  sim.DescribeParameter("GullyEndYear",0,"",[]float64{ 0, 0 },"",GullyEndYearDims),
  sim.DescribeParameter("Area",0,"m^2",[]float64{ 0, 0 },"",AreaDims),
  sim.DescribeParameter("averageGullyActivityFactor",0,"",[]float64{ 0, 3 },"",averageGullyActivityFactorDims),
  sim.DescribeParameter("GullyAnnualAverageSedimentSupply",0,"t.yr^-1",[]float64{ 0, 0 },"",GullyAnnualAverageSedimentSupplyDims),
  sim.DescribeParameter("GullyPercentFine",0,"Average clay + silt percentage of gully material",[]float64{ 0, 0 },"",GullyPercentFineDims),
  sim.DescribeParameter("managementPracticeFactor",0,"",[]float64{ 0, 0 },"",managementPracticeFactorDims),
  sim.DescribeParameter("longtermRunoffFactor",0,"",[]float64{ 0, 0 },"",longtermRunoffFactorDims),
  sim.DescribeParameter("dailyRunoffPowerFactor",0,"",[]float64{ 0, 0 },"",dailyRunoffPowerFactorDims),
  sim.DescribeParameter("sdrFine",0,"",[]float64{ 0, 0 },"",sdrFineDims),
  sim.DescribeParameter("sdrCoarse",0,"",[]float64{ 0, 0 },"",sdrCoarseDims),
  sim.DescribeParameter("timeStepInSeconds",86400,"s Duration of timestep in seconds",[]float64{ 0, 1e+08 },"",timeStepInSecondsDims),}

  result.Inputs = []string{
  "quickflow","year","AnnualRunoff","annualLoad",}
  result.Outputs = []string{
  "fineLoad","coarseLoad","generatedFine","generatedCoarse",}

  result.States = []string{
  }

  result.Dimensions = []string{
      }
	return result
}

func (m *DynamicSednetGully) InitialiseDimensions(dims []int) {
  
}

func (m *DynamicSednetGully) FindDimensions(parameters data.ND2[float64]) []int {
  
  return []int{}
  
}




func (m *DynamicSednetGully) InitialiseStates(n int) data.ND2[float64] {
  // Zero states
	var result = data.NewArray2D[float64](n,0)

	// for i := 0; i < n; i++ {
  //   stateSet := make(sim.StateSet,0)
  //   

  //   if result==nil {
  //     result = data.NewArray2D[float64](stateSet.Len(0),n)
  //   }
  //   result.Apply([]int{0,i},[]int{1,1},stateSet)
	// }
 
	return result
}



func (m *DynamicSednetGully) Run(inputs data.ND3[float64], states data.ND2[float64], outputs data.ND3[float64]) {

  // Loop over all cells
  inputDims := inputs.Shape()
  numCells := states.Len(sim.DIMS_CELL)
  numStates := states.Len(sim.DIMS_STATE)
  numInputSequences := inputs.Len(sim.DIMI_CELL)

  //  fmt.Println("num cells",lenStates,"num states",numStates)
  // fmt.Println("states shape",states.Shape())
  // fmt.Println("states",states) 
  inputLen := inputDims[sim.DIMI_TIMESTEP]
  cellInputsShape := inputDims[1:]
  inputNewShape := []int{inputLen}

//  outputPosSlice := outputs.NewIndex(0)
  outputStepSlice := outputs.NewIndex(1)
  outputSizeSlice := outputs.NewIndex(1)
  outputSizeSlice[sim.DIMO_TIMESTEP] = inputLen

//  statesPosSlice := states.NewIndex(0)
  statesSizeSlice := states.NewIndex(1)
  statesSizeSlice[sim.DIMS_STATE] = numStates

//  inputsPosSlice := inputs.NewIndex(0)
  inputsSizeSlice := inputs.NewIndex(1)
  inputsSizeSlice[sim.DIMI_INPUT] = inputDims[sim.DIMI_INPUT]
  inputsSizeSlice[sim.DIMI_TIMESTEP] = inputLen

//  var result sim.RunResults
//	result.Outputs = data.NewArray3D[float64]( 4, inputLen, numCells)
//	result.States = states  //clone? make([]sim.StateSet, len(states))

  doneChan := make(chan int)
  // fmt.Println("Running DynamicSednetGully for ",numCells,"cells")
//  for i := 0; i < numCells; i++ {
  for j := 0; j < numCells; j++ {
    go func(i int){
      outputPosSlice := outputs.NewIndex(0)
      statesPosSlice := states.NewIndex(0)
      inputsPosSlice := inputs.NewIndex(0)

      outputPosSlice[sim.DIMO_CELL] = i
      statesPosSlice[sim.DIMS_CELL] = i
      inputsPosSlice[sim.DIMI_CELL] = i%numInputSequences

      yeardisturbance := m.YearDisturbance[i%len(m.YearDisturbance)]
      gullyendyear := m.GullyEndYear[i%len(m.GullyEndYear)]
      area := m.Area[i%len(m.Area)]
      averagegullyactivityfactor := m.averageGullyActivityFactor[i%len(m.averageGullyActivityFactor)]
      gullyannualaveragesedimentsupply := m.GullyAnnualAverageSedimentSupply[i%len(m.GullyAnnualAverageSedimentSupply)]
      gullypercentfine := m.GullyPercentFine[i%len(m.GullyPercentFine)]
      managementpracticefactor := m.managementPracticeFactor[i%len(m.managementPracticeFactor)]
      longtermrunofffactor := m.longtermRunoffFactor[i%len(m.longtermRunoffFactor)]
      dailyrunoffpowerfactor := m.dailyRunoffPowerFactor[i%len(m.dailyRunoffPowerFactor)]
      sdrfine := m.sdrFine[i%len(m.sdrFine)]
      sdrcoarse := m.sdrCoarse[i%len(m.sdrCoarse)]
      timestepinseconds := m.timeStepInSeconds[i%len(m.timeStepInSeconds)]
      

      // fmt.Println("i",i)
      // fmt.Println("States",states.Shape())
      // fmt.Println("Tmp2",tmp2.Shape())
      

      
      
      

  //    fmt.Println("is",inputDims,"tmpShape",tmpCI.Shape(),"cis",cellInputsShape)

      cellInputs := inputs.Slice(inputsPosSlice,inputsSizeSlice,nil).MustReshape(cellInputsShape)
  //    fmt.Println("cellInputs Shape",cellInputs.Shape())
      
  //    fmt.Println("{quickflow m^3.s^-1}",tmpTS.Shape())
      quickflow := cellInputs.Slice([]int{ 0,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{year year}",tmpTS.Shape())
      year := cellInputs.Slice([]int{ 1,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{AnnualRunoff mm.yr^-1}",tmpTS.Shape())
      annualrunoff := cellInputs.Slice([]int{ 2,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      
  //    fmt.Println("{annualLoad }",tmpTS.Shape())
      annualload := cellInputs.Slice([]int{ 3,0}, []int{ 1,inputLen}, nil).MustReshape(inputNewShape).Unroll()
      

      

      
      
      outputPosSlice[sim.DIMO_OUTPUT] = 0
      fineload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 1
      coarseload := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 2
      generatedfine := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      outputPosSlice[sim.DIMO_OUTPUT] = 3
      generatedcoarse := outputs.Slice(outputPosSlice,outputSizeSlice,outputStepSlice).MustReshape([]int{inputLen}).Unroll()
      
      

       sednetGullyOrig(quickflow,year,annualrunoff,annualload,yeardisturbance,gullyendyear,area,averagegullyactivityfactor,gullyannualaveragesedimentsupply,gullypercentfine,managementpracticefactor,longtermrunofffactor,dailyrunoffpowerfactor,sdrfine,sdrcoarse,timestepinseconds,fineload,coarseload,generatedfine,generatedcoarse)

      
      
      

  //		result.Outputs.ApplySpice([]int{i,0,0},[]int = make([]sim.Series, 4)
      

      doneChan <- i
    }(j)
	}

  for j := 0; j < numCells; j++ {
    <- doneChan
  }
//	return result
}
