name: build-ow-core
on:
  push:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: ./build/ci/all.sh
        - name: upload build
          uses: actions/upload-artifact@v2
          with:
            name: linux-${{ github.sha }}
            path: |
              ow-inspect
              ow-single
              ow-sim
              ows-ensemble
              libopenwater.h
              libopenwater.so
  build-windows:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - run: ./build/ci/all.sh
        - name: upload build
          uses: actions/upload-artifact@v2
          with:
            name: windows-${{ github.sha }}
            path: |
              *.exe
              1.8.21/bin/*.dll
              libopenwater.h
              libopenwater.so
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build/ci/all.sh
      # - name: upload build
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: macos-${{ github.sha }}
      #     path: |
      #       *.exe
      #       1.8.21/bin/*.dll
      #       libopenwater.h
      #       libopenwater.so



